version: '3'

services:
  api:
    image: pichonga/backend:latest
    ports:
      - 3000:3000
    networks:
      - redDocker
      
  db:
    image: mongo
    volumes:
      - ./mongo.js:/docker-entrypoint-initdb.d/mongo-init.js
    
    networks:
      - redDocker
      

networks:
  redDocker:
