name: script build push

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install
      run: npm install
    
    - name: build dist
      run: npx tsc

    - name: copy env
      run: cp .env dist/.env
      
    - name: Build
      run: docker build -t pichonga/backend:${{ github.sha }} .
      
    - name: Login
      run: docker login -u pichonga -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push
      run: docker push pichonga/backend:${{ github.sha }}
